#include <std_include.hpp>
#include "getbots_command.hpp"

#include "../console.hpp"

const char* getbots_command::get_command() const
{
	return "getbots";
}

void getbots_command::handle_command(const network::address& target, const std::string_view&)
{
	static const std::array bot_names
	{
		"6arelyhuman",
		"aerosoul",
		"All Night",
		"Ash",
		"avail",
		"barbie slut",
		"Barbie Whore",
		"Bimbo Suicide",
		"bimbo",
		"Blow Up!",
		"Boston",
		"Bubbles",
		"Caliber",
		"CAPTAINJERKFACE",
		"Catalyst",
		"Cenote",
		"Chicago",
		"clang",
		"Cressi",
		"DANCE! Till We Die",
		"David Guetta",
		"Death city",
		"Debian",
		"Devil's Spring",
		"Diamante",
		"Diavolo",
		"Disgusting",
		"DKo5",
		"Do U Luv Me",
		"Do U",
		"Don't Like Anybody",
		"don't touch my hair",
		"drama queenz",
		"Dsso",
		"Eagle's Nest",
		"Eat Me",
		"Evan",
		"Eyelashes on",
		"feeling nothing",
		"Flex190",
		"FOURZEROTWO",
		"FragsAreUs",
		"FryTechTip",
		"Furry",
		"FutureRave",
		"Ginnie Springs",
		"Girl",
		"Go Crazy",
		"gsc-tool",
		"H3X1C",
		"Hands up!",
		"Hey Dj",
		"Higher",
		"homura",
		"Horizon - SCR",
		"Hypocrite",
		"INeedGames",
		"Infamous",
		"Inferno",
		"InfinityScript",
		"Jack Back",
		"JetFins",
		"JezuzLizard",
		"Joe Biden",
		"Joel",
		"King Crimson",
		"KiraFoxAF",
		"KonaFuzzButt",
		"Laupetin",
		"Level Up!",
		"Lifeline",
		"Like a G6",
		"llvm-project",
		"Loba",
		"Loona",
		"Loudward",
		"Louvenarde",
		"Mares",
		"momo5502",
		"Montreal",
		"MSVC",
		"MUPP",
		"mxve",
		"My Flaws",
		"Neapolis",
		"New York",
		"Nightzy",
		"Non-binary Jesus",
		"OneFourOne",
		"OpenAssetTools",
		"pgriffin69x",
		"Poker Face",
		"Portofino",
		"PottyMouth",
		"RaidMax",
		"ramzi1337hak0r",
		"RektInator",
		"Resxt",
		"rEvoRebreather",
		"RezTech",
		"Roxie",
		"Santi Diving",
		"saysupshelly",
		"Scarlxrd",
		"scene high",
		"SCUBAPRO",
		"Slay Everyday",
		"Sloth",
		"SLUT SZN",
		"Snake",
		"Sparky",
		"st0rm",
		"Stalk Me",
		"StarBerry",
		"Titanium",
		"Trimix",
		"turn it up",
		"TwinLeaf",
		"ur my heroin",
		"Ur Vampire",
		"Valkyrie",
		"Vore",
		"Wanted",
		"Wattson",
		"Wereric",
		"X Party",
		"xensik",
		"XOXO (Kisses Hugs)",
		"XXXTENSIONS",
		"You & Me",
		"Yummy",
		"ZoneBuilder",
		"ZoneTool",
	};

	std::stringstream stream{};
	for (const auto& bot : bot_names)
	{
		stream << bot << std::endl;
	}

	this->get_server().send(target, "getbotsResponse", stream.str());
	console::log("Sent bot names: %s", target.to_string().data());
}
